version: "3.8"

services:
  db:
    container_name: sqlserver
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SERVER_SA_PASSWORD}
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
